name: Bump python image

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-chainguard-images:
    runs-on: ubuntu-latest
    steps:
      - name: bump python image
        uses: digitalservicebund/bump-chainguard-digest@4a81196c94ada7ab6841a963e62b9a4103070575
        with:
          image_name: python
          file_path: Dockerfile
          github_token: ${{ github.token }}
          branch: 'bump-python-image'
      - name: bump python-dev image
        uses: digitalservicebund/bump-chainguard-digest@4a81196c94ada7ab6841a963e62b9a4103070575
        with:
          image_name: python:latest-dev
          file_path: Dockerfile
          github_token: ${{ github.token }}
          branch: 'bump-python-dev-image'
#      - name: Send status to Slack
#        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 #v1.6.1
#        if: ${{ failure() }}
#        with:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
