name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 2" # Every Tuesday at midnight UTC
  # also: allow to run this workflow manually
  workflow_dispatch:

jobs:
  #############################################
  # jobs dispatched to a separate workflow file
  #############################################

  backend-jobs:
    permissions:
      security-events: write
      packages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/backend-jobs.yml
    with:
      container-registry: ghcr.io
      container-image-name: ${{ github.repository }}
      container-image-version: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  create-docker-image-job:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') || contains(github.event.labeled.labels.*.name, 'dev-env') }}
    permissions:
      security-events: write
      packages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/create-docker-image-job.yml
    with:
      container-registry: ghcr.io
      container-image-name: ${{ github.repository }}
      container-image-version: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  push-docker-image-job:
    if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'dev-env') || contains(github.event.labeled.labels.*.name, 'dev-env') }}
    needs:
      - backend-jobs
      - create-docker-image-job
    permissions:
      security-events: write
      packages: write
      id-token: write
      contents: read
    uses: ./.github/workflows/push-docker-image-job.yml
    with:
      container-registry: ghcr.io
      container-image-name: ${{ github.repository }}
      container-image-version: ${{ github.event.pull_request.head.sha || github.sha }}
    secrets: inherit

  # ######################
  # Deploy new versions to staging
  # ######################

  deploy-staging-job:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - backend-jobs
      - push-docker-image-job
    permissions:
      id-token: write
    uses: ./.github/workflows/deploy-staging-job.yml
    secrets: inherit

  talisman-check:
    runs-on: ubuntu-latest
    # Running on main only https://digitalservicebund.slack.com/archives/C046VD44ZEH/p1706516240974409
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Detect secrets in incoming commits with Talisman
        uses: digitalservicebund/talisman-secrets-scan-action@550e4a1e0aee7921b5df1fc0f02bc6adfa784bd2
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 #v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}

  push-reports:
    runs-on: ubuntu-latest
    env:
      REPORTS_REPOSITORY: digitalservicebund/ris-reports
    needs:
      - backend-jobs
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
    steps:
      # Collect ADRs
      - name: ADRs - Checkout ris-pdf-printservice repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          path: ris-pdf-printservice
      - name: ADRs - Copy to temp folder
        run: |
          mkdir -p tmp/adr-source
          find ris-pdf-printservice/doc/adr/ -type f ! -name '0000-template.md' -exec cp {} tmp/adr-source/ \;
          ls -l tmp/adr-source

      # ADRs
      - name: ADRs - git add report
        uses: digitalservicebund/add-ris-report@31a248ea368f94bfa3a012da3c202bcc6be2debe
        with:
          filePath: tmp/adr-source
          destinationDir: adr/ris-pdf-printservice
          reportIsDirectory: true
          keepAllVersions: false # don't need the timestamped snapshots of the whole folder
          BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}

      # Licence reports
      - name: Licence report - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: licence-reports
          path: tmp/licence-reports/
          merge-multiple: true
      - name: Licence report - git add report
        uses: digitalservicebund/add-ris-report@31a248ea368f94bfa3a012da3c202bcc6be2debe
        with:
         filePath: tmp/licence-reports/licence-report.csv
         destinationDir: licence-reports/backend/ris-pdf-printservice
         BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
         BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}

       # Test report
      - name: Test report - Download
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c
        with:
          name: test-reports
          path: tmp/test-reports
      - name: Test report - git add report
        uses: digitalservicebund/add-ris-report@31a248ea368f94bfa3a012da3c202bcc6be2debe
        with:
          filePath: tmp/test-reports
          destinationDir: test-reports/ris-pdf-printservice/tests
          reportIsDirectory: true
          BUCKET_ACCESS_KEY_ID: ${{ secrets.REPORTS_BUCKET_ACCESS_KEY_ID }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.REPORTS_BUCKET_SECRET_ACCESS_KEY }}
      - name: Send status to Slack
        uses: digitalservicebund/notify-on-failure-gha@671832f192aee0a068fd92b2f6deb975df794a84 #v1.6.1
        if: ${{ failure() && github.ref == 'refs/heads/main' }}
        with:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ vars.SLACK_CHANNEL_ID }}
